config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get '/', to: 'users/sessions#new'
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :users, only: [:index, :show] do
    resources :tasks do
      member do
        patch 'done'
      end
    end
    
    resources :relationships, only: [:create, :destroy]
    member do
      get 'follows'
      get 'followers'
      get 'follow_tasks'
    end
  end
  
  resources :rooms, only: [:create, :show]
  resources :messages, only: :create
  
  resources :tasks do
    resources :likes, only: [:create, :destroy]
  end

  resources :communities do
    resources :chats, only: [:index, :create, :destroy]
    resources :questions do
      patch 'resolve', on: :member
    end
  end

  post 'communities/:id', to: 'communities#join'
  delete 'communities/:id/exit', to: 'communities#exit', as: 'exit_community'

  resources :questions do
    resources :answers, only: [:create, :destroy]
    resources :me_toos, only: [:create, :destroy]
    resources :goods, only: [:create, :destroy]
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :community
  has_one_attached :image
  has_many :answers, dependent: :destroy
  has_many :me_toos, dependent: :destroy
  has_many :goods, dependent: :destroy

  validates :title, :content, presence: true
  validates :state, inclusion: { in: [true, false] }
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_community
  before_action :set_question, only: [:show, :edit, :update, :destroy, :resolve]
  before_action :move_to_index, except: [:index, :show]
  before_action :configure_author, only: [:edit, :update, :resolve]
  before_action :answer_new, only: [:show, :create, :update, :resolve]
  before_action :set_answers, only: [:show, :update, :resolve]

  def index
    @questions = @community.questions.preload(:me_toos, :goods).order("created_at DESC")
    # サイドバー用データ取得
    @joined_users = @community.joined_users
    @tasks = Task.user_is(@joined_users.pluck(:id))
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to community_question_path(@community, @question)
    else
      render :new
    end
  end

  def show
    # サイドバー用データ取得
    @joined_users = @community.joined_users
    @tasks = Task.user_is(@joined_users.pluck(:id))
    @questions = @community.questions
  end

  def edit
  end

  def update
    if @question.update(question_params)
      redirect_to community_question_path(@community, @question)
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to community_questions_path(@community)
  end

  # 受付→解決済みに変更する
  def resolve
    if @question.state
      @question.update(state: 0)
      redirect_to community_question_path(@community)
    else
      @question.update(state: 1)
      redirect_to community_question_path(@community)
    end
  end

  private

  def set_community
    @community = Community.find(params[:community_id])
  end

  def set_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :content, :image).merge(user_id: current_user.id, community_id: params[:community_id])
  end

  def move_to_index
    set_community
    redirect_to community_questions_path(@community) unless current_user.already_joined?(@community)
  end

  def configure_author
    set_question
    redirect_to community_question_path(@community, @question) if current_user.id != @question.user.id
  end

  def answer_new
    @answer = Answer.new
  end

  def set_answers
    set_question
    @answers = @question.answers.includes(:user).order("created_at DESC")
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_question_post_form.html.erb
<%= form_with model: [community, question], local: true do |f|%>
  <%= render 'shared/error_messages', model: f.object %>
  <div class="question-form-item">
    <%= f.label "タイトル", class:"question-label"%>
    <%= f.text_field :title, class:"question-input" %>
  </div>
  <div class="question-form-item">
    <%= f.label "内容", class:"question-label"%>
    <%= f.text_area :content, class:"question-input text" %>
  </div>
  
  <div class="question-form-item">
    <%= f.label "画像", class:"question-label"%>
    <%= f.file_field :image %>
  </div>

  <%= f.submit "投稿", class:"question-submit btn" %>
<% end %>

app/views/questions/edit.html.erb
<div class="menu-bar">
</div>
  
<div class="main">
  <div class="question-post-form">
    <%= render partial: "question_post_form", locals: { community: @community, question: @question } %>
    <%= link_to "削除する", community_question_path(@community, @question), method: :delete, class:"delete-btn" %>
  </div>
</div>

app/views/questions/index.html.erb
<%= render "communities/community_sidebar" %>
  
<div class="main">
  <div class="community-main-heading">
    <div class="community-main-menu">
      <%= link_to community_path(@community), class:"community-navigation" do %>
        <%= image_tag "check.png", size: "18x18", class: "task-icon" %><span>みんなのタスク</span>
      <% end %>
      <%= link_to community_chats_path(@community), class:"community-navigation" do %>
        <%= image_tag "chat_man.png", size: "18x18", class: "chat-icon" %><span>チャット</span>
      <% end %>
      <%= link_to community_questions_path(@community), class:"community-navigation question" do %>
        <%= image_tag "question.png", size: "18x18", class: "question-icon" %><span>質問</span>
      <% end %>
    </div>
  </div>
  <div class="question-index-area">
    <div class="communities-main-menu-under">
      <% if current_user.already_joined?(@community) %>
          <%= link_to "質問する", new_community_question_path, class:"create-question btn" %>
      <% else %>
        <p class="need-join-message">質問投稿にはコミュニティ参加が必要です</p>
      <% end %>
    </div>
    <div class="question-cards">
      <% @questions.each do |question| %>
        <%= link_to community_question_path(@community, question) do %>
          <div class="question-summary-card">
            <div class="question-summary-head">
              <span class="question-title"><%= question.title %>
              <span class="question-date"><%= l question.created_at, format: :short %></span> 
            </div>
            <div class="question-summary-status">
              <div class="question-summary-response">
                <span class="question-summary-metoo">知りたい！<%= question.me_toos.length %></span>
                <span class="question-summary-good">役に立った！<%= question.goods.length %></span>
              </div>
              <% if question.state %>
                <span class="question-summary-close">解決済み</span>
              <% else %>
                <span class="question-summary-open">受付中</span>
              <% end %>
            </div>
            <div class="like-area">
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/questions/new.html.erb
<div class="menu-bar">
</div>
  
<div class="main">
  <div class="question-post-form">
    <%= render partial: "question_post_form", locals: { community: @community, question: @question } %>
  </div>
</div>

app/views/questions/show.html.erb
<%= render partial: "communities/community_sidebar" %>

<div class="main">
  <div class="community-main-heading">
    <div class="community-main-menu">
      <%= link_to community_path(@community), class:"community-navigation" do %>
        <%= image_tag "check.png", size: "18x18", class: "task-icon" %><span>みんなのタスク</span>
      <% end %>
      <%= link_to community_chats_path(@community), class:"community-navigation" do %>
        <%= image_tag "chat_man.png", size: "18x18", class: "chat-icon" %><span>チャット</span>
      <% end %>
      <%= link_to community_questions_path(@community), class:"community-navigation question" do %>
        <%= image_tag "question.png", size: "18x18", class: "question-icon" %><span>質問</span>
      <% end %>
    </div>
  </div>
  <div class="question-and-answer-area">
    <div class="question-area">
      <%= link_to "<< 一覧にもどる", community_questions_path(@community), class:"back-questions-btn" %>
      <div class="question-card">
        <div class="question-user">
          <% if @question.user.profile.image.present? %>
            <%= link_to image_tag(@question.user.profile.image.variant(resize: "50x50"), class:"user-image"), user_path(@question.user) %>
          <% end %>
          <%= link_to @question.user.name, user_path(@question.user), class:"question-user-name" %>
        </div>
        <div class="question-title">
          <%= @question.title %>
          <% if @question.user.id == current_user.id %>
            <%= link_to "編集する", edit_community_question_path(@community, @question), class:"edit-btn" %>
          <% end %>
        </div>
        <div class="question-content">
          <%= @question.content %>
        </div>
        <% if @question.image.present? %>
          <%= image_tag @question.image.variant(resize: "500x500"), class:"question-image" %>
        <% end %>

        <div class="question-response-area">
          <div id="question_<%= @question.id %>">
            <%= render partial: "shared/me_too", locals: { question: @question } %>
          </div>

          <div id="good_question_<%= @question.id %>">
            <%= render partial: "shared/good", locals: { question: @question } %>
          </div>

          <% if @question.state %>
            <%= link_to "解決済み", resolve_community_question_path(@community, @question), method: :patch, class:"question-close btn" %>
          <% else %>
            <%= link_to "受付中", resolve_community_question_path(@community, @question), method: :patch, class:"question-open btn" %>
          <% end %>
        </div>

      </div>
    </div>
    <div class="answer-area">
      <p class="answer-label">コメント一覧</p>
      <% @answers.each do |answer| %>
        <div class="answer-card">
          <div class="answer-user">
            <% if answer.user.profile.image.present? %>
              <%= link_to image_tag(answer.user.profile.image.variant(resize: "50x50"), class:"user-image"), user_path(answer.user) %>
            <% end %>
            <%= link_to answer.user.name, user_path(answer.user), class:"answer-user-name" %>
          </div>
          <div class="answer-comment">
            <%= answer.text %>
          </div>
        </div>
      <% end %>
      <%= form_with model: [@question, @answer], local: true, class:"answer-form-area" do |f| %>
        <p class="answer-form-label">コメントする</p>
        <%= f.text_area :text, placeholder:"回答してみよう！", class:"answer-form" %>
        <%= f.submit "投稿", class:"answer-submit btn" %>
      <% end %>
    </div>
  </div>
</div>