config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get '/', to: 'users/sessions#new'
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :users, only: [:index, :show] do
    resources :tasks do
      member do
        patch 'done'
      end
    end
    
    resources :relationships, only: [:create, :destroy]
    member do
      get 'follows'
      get 'followers'
      get 'follow_tasks'
    end
  end
  
  resources :rooms, only: [:create, :show]
  resources :messages, only: :create
  
  resources :tasks do
    resources :likes, only: [:create, :destroy]
  end

  resources :communities do
    resources :chats, only: [:index, :create, :destroy]
    resources :questions do
      patch 'resolve', on: :member
    end
  end

  post 'communities/:id', to: 'communities#join'
  delete 'communities/:id/exit', to: 'communities#exit', as: 'exit_community'

  resources :questions do
    resources :answers, only: [:create, :destroy]
    resources :me_toos, only: [:create, :destroy]
    resources :goods, only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates :password, format: { with: PASSWORD_REGEX, message: "は半角英数字で入力してください" }, on: :create

  has_one :profile, dependent: :destroy
  accepts_nested_attributes_for :profile, update_only: true
  has_many :tasks, dependent: :destroy

  has_many :user_rooms, dependent: :destroy
  has_many :rooms, through: :user_rooms
  has_many :messages, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :own_communities, class_name: "Community", dependent: :destroy
  has_many :user_communities, dependent: :destroy
  has_many :communities, through: :user_communities
  has_many :chats, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :me_toos, dependent: :destroy
  has_many :goods, dependent: :destroy

  # フォロー側
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id, dependent: :destroy
  has_many :followings, through: :active_relationships, source: :follower
  # フォロワー側
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id, dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :following

  # 引数のユーザが既にフォローしているかどうかの確認
  def follow?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end

  # 引数のtaskにいいね済みかどうかの確認
  def already_liked?(task)
    likes.where(task_id: task.id).exists?
  end

  # 引数のcommunityに参加済みかどうかの確認
  def already_joined?(community)
    user_communities.where(community_id: community.id).exists?
  end

  # 引数のquestionに「知りたい！」済みかどうかの確認
  def already_me_too?(question)
    me_toos.where(question_id: question.id).exists?
  end

  # 引数のquestionに「役に立った！」済みかどうかの確認
  def already_good?(question)
    goods.where(question_id: question.id).exists?
  end

  # ユーザ検索
  scope :search, -> (search_params) do
    # search_paramsが無かったら実行しない
    return if search_params.blank?

    # profileのtextが一致したuser
    profiles_text_match = Profile.text_like(search_params[:text])
    # profileのoccupationが一致したuser
    profiles_occupation_match = Profile.occupation_is(search_params[:occupation_id])

    # nameまたはprofileで取得したuser、かつ、occupationで取得したuser
    where("name LIKE ?", "%#{search_params[:text]}%")
      .or(where(id: profiles_text_match.pluck(:user_id)))
      .where(id: profiles_occupation_match.pluck(:user_id))
  end

  # ゲストユーザログイン時に「ゲスト」を検索or作成
  def self.guest
    find_or_create_by!(email: "guest@guest.com") do |user|
      user.name = "ゲスト"
      user.password = SecureRandom.hex(10)
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  def new
    @user = User.new
    @profile = @user.build_profile
  end

  def create
    @user = User.new(sign_up_params)
    @profile = @user.build_profile(sign_up_params[:profile_attributes])
    @profile.image_added?
    if @user.valid?
      @user.save
      @profile.save
      sign_in(:user, @user)
      redirect_to user_path(@user)
    else
      render action: :new
    end
  end

  def edit
    @user = current_user
    @profile = @user.profile
  end

  def update
    @user = User.find(current_user.id)
    @profile = @user.profile
    if @user.update(account_update_params)
      @user.profile.update(account_update_params[:profile_attributes])
      sign_in(:user, @user)
      redirect_to user_path(@user)
    else
      render action: :edit
    end
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # ログイン後にマイページに遷移する
  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  # ログアウト後にログイン画面に遷移する
  def after_sign_out_path_for(resource)
    new_user_session_path
  end

  # ゲストユーザーログイン
  def guest_sign_in
    user = User.guest
    # プロフィール登録
    profile = user.build_profile(occupation_id: 1, text: "ゲストユーザーです。よろしくお願いします", user_id: user.id)
    profile.image.attach(io: File.open('app/assets/images/default_user_image.png'), filename: 'default_user_image.png')
    profile.save

    sign_in(user)
    redirect_to '/'
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :follow_tasks, :follows, :followers]

  def index
    @search_params = user_search_params
    # @users = User.search(@search_params).includes(:profile)
    @users = User.search(@search_params).includes(profile: { image_attachment: :blob })
  end

  def show
    @tasks = @user.tasks.not_completed.order("created_at DESC")
    # @tasks = Task.user_is(@user.id).not_completed.order("created_at DESC")
    @following_users = @user.followings
    @follower_users = @user.followers

    # タスク投稿フォーム用
    @task = Task.new

    # DM用するボタンのためのデータ取得
    # user_roomから自分が含まれるidを取得
    room_ids = current_user.user_rooms.pluck(:room_id)
    # 取得したuser_roomのうち、自分と相手のペアを探す
    target_user_room = UserRoom.find_by(room_id: room_ids, user_id: @user.id)
    # 特定したuser_roomからroom_idを取得する
    @room = target_user_room.room if target_user_room.present?
  end

  def follow_tasks
    @following_users = @user.followings
    @follow_user_tasks = Task.where(user_id: @following_users.pluck(:id)).not_completed.order("created_at DESC").includes(user: { profile: { image_attachment: :blob } })
    @follower_users = @user.followers
    @task = Task.new
  end

  # フォロー数
  def follows
    @following_users = @user.followings.includes(profile: { image_attachment: :blob })
  end

  # フォロワー数
  def followers
    @follower_users = @user.followers.includes(profile: { image_attachment: :blob })
  end

  private

  def set_user
    @user = User.find(params[:id])
    @profile = @user.profile
  end

  def user_search_params
    params.fetch(:search, {}).permit(:occupation_id, :text)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_sidebar.html.erb
<div class="menu-bar">
  <div class="menu-bar-box">
    <div>
      <% if @profile.image.present? %>
        <%= image_tag @profile.image.variant(resize: "200x200"), class:"profile-image" %>
      <% end %>
    </div>
    <div class="user-name"><%= @user.name %></div>
    <div class="user-text"><%= @user.profile.text %></div>
    <div class="menu-items">
      <div class="relationships">
        <% if @user != current_user %>
          <% if @user.follow?(current_user) %>
            <%= link_to  user_relationship_path(@user), method: :delete, class:"unfollow-link" do %>
              <span class="unfollow-btn"><i class="fas fa-user-check"></i>フォロー済み</span> 
            <% end %>
          <% else %>
            <%= link_to user_relationships_path(@user), method: :post, class:"follow-link" do %>
              <span class="follow-btn"><i class="fas fa-user-check"></i>フォローする</span>
            <% end %>
          <% end %>
        <% end %>
      </div>
      <div class="relationships-user">
        <%= link_to follows_user_path(@user) do %>
          <span class="follow-count"><i class="fas fa-user-friends"></i>フォロー<%= " #{@following_users.count}" %></span>
        <% end %>
        <span class="follow-btn-separater">|</span>
        <%= link_to followers_user_path(@user) do %>
          <span class="follower-count">フォロワー<%= " #{follower_users.count}" %></span>
        <% end %>
      </div>
      <div class="direct-message">
        <% if current_user != @user %>
          <% if @room.present? %>
            <%= link_to room_path(@room.id) do %>
              <span class="message-btn"><i class="far fa-envelope"></i>メッセージを送る</span>
            <% end %>
          <% elsif %>
            <%= link_to rooms_path(@user.id), method: :post do %>
              <span class="message-btn"><i class="far fa-envelope"></i>メッセージを送る</span>
            <% end %>
          <% end %>
        <% end %>
      </div>
      <div class="completed-task">
        <%= link_to user_tasks_path(@user.id) do %>
          <span class="completed-task-count"><span>完了タスク数</span><%= @user.tasks.where(state: true).count %></span>
        <% end %><span><%= " /#{@user.tasks.count}" %></span>
      </div>
      <%if current_user == @user %>
        <%= link_to " 編集する", edit_user_registration_path(@user), class:"edit" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_users_index.html.erb
<% users.each do |user| %>
    <div class="user-card">
      <div class="user-card-head">
        <% if user.profile.image.present? %>
          <%= link_to image_tag(user.profile.image.variant(resize: "50x50"), class:"user-image"), user_path(user) %>
        <% end %>
        <%= link_to user.name, user_path(user), class:"user-name" %>
      </div>
      <div class="user-text">
        自己紹介：<%= user.profile.text %>
      </div>
      <div class="user-occupation">
        職種：<%= user.profile.occupation_name(user) %>
      </div>
    </div>
<% end %>

app/views/users/follow_tasks.html.erb
<%= render partial: "users/sidebar", locals: { user: @user, profile: @profile, following_users: @following_users, follower_users: @follower_users, room: @room } %>
  
<div class="main">
  <div class="tasks-heading">
    <% if user_signed_in? && (current_user.id == @user.id) %>
      <div class="tasks-heading-navi-box">
        <%= link_to "マイタスク", user_path(current_user), class:"tasks-heading-navi" %>
        <%= link_to "仲間のタスク", follow_tasks_user_path(current_user), class:"tasks-heading-navi follow-tasks" %>
      </div>
    <% end %>  
  </div>
  <div class="posts">
    <span class="task-index-comment">タスク一覧</span>
    <div class="follow-posts-cards">
      <% @follow_user_tasks.each do |task| %>
        <div id="task_<%= task.id %>">
          <%= render partial: "shared/tasks", locals: { task: task } %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="right-bar">
  <div class="right-bar-box">
    <span class="coming-soon">Coming Soon!</span>
  </div>
</div>

app/views/users/followers.html.erb
  <div class="menu-bar">

  </div>
    
  <div class="main">
    <div class="following-user-name-heading">
      <%= link_to @user.name, user_path(@user), class:"following-user-name" %>のフォロワー
    </div>
    <div class="user-index-area">
      <div class="user-cards">
        <%= render partial: "users_index", locals: { users: @follower_users  } %>
      </div>
    </div>
  </div>

app/views/users/follows.html.erb
  <div class="menu-bar">
    
  </div>
    
  <div class="main">
    <div class="following-user-name-heading">
      <%= link_to @user.name, user_path(@user), class:"following-user-name" %>のフォロー
    </div>
    <div class="user-index-area">
      <div class="user-cards">
        <%= render partial: "users_index", locals: { users: @following_users  } %>
      </div>
    </div>
  </div>

app/views/users/index.html.erb
<div class="menu-bar">
  <div class="menu-bar-box">
    <p class="menu-bar-head"><i class="fas fa-search"></i>ユーザー検索</p>
    <div class="menu-items">
      <%= form_with scope: :search, url: users_path, method: :get, local: true do |f| %>
        <div class="search-field">
          <%= f.label :text, "キーワード", class:"search-label" %>
          <%= f.text_field :text, value: @search_params[:text], class:"search-text" %>
        </div>
        <div class="search-field">
          <%= f.label :occupation_id, "職種", class:"search-label" %>
          <%= f.collection_select(:occupation_id, Occupation.all, :id, :name, {selected: @search_params[:occupation_id], include_blank: "選択しない"}, {class:"search-occupation"}) %>
        </div>
        <div class="search-btn-area">
          <%= f.submit "検索", class:"search btn" %>
        </div>
      <% end %>
      <div class="search-cancel">
        <%= link_to "検索解除", users_path, class:"search-cancel-btn" %>
      </div> 
    </div>
  </div>
</div>
  
<div class="main">
  <div class="search-heading">
    <div class="search-menu">
      <%= link_to "ユーザー", users_path, class:"search-navigation users" %>
      <%= link_to "コミュニティ", communities_path, class:"search-navigation" %>
    </div>
  </div>
  <div class="user-index-area">
    <div class="user-cards">
      <%= render partial: "users_index", locals: { users: @users } %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= render partial: "users/sidebar", locals: { user: @user, profile: @profile, following_users: @following_users, follower_users: @follower_users, room: @room } %>
  
<div class="main">
  <div class="tasks-heading">
    <% if user_signed_in? && (current_user.id == @user.id) %>
      <div class="tasks-heading-navi-box">
        <%= link_to "マイタスク", user_path(current_user), class:"tasks-heading-navi my-tasks" %>
        <%= link_to "仲間のタスク", follow_tasks_user_path(current_user), class:"tasks-heading-navi" %>
      </div>
      <%= render partial: "tasks/task_form", locals: { user: @user, task: @task } %>
    <% end %>  
  </div>
  <div class="user-posts">
    <span class="task-index-comment">タスク一覧</span>
    <div class="posts-cards", id="postCards">
      <% @tasks.each do |task| %>
        <div id="task_<%= task.id %>">
          <%= render partial: "shared/tasks", locals: { task: task } %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="right-bar">
  <div class="right-bar-box">
    <span class="coming-soon">Coming Soon!</span>
  </div>
</div>