config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get '/', to: 'users/sessions#new'
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :users, only: [:index, :show] do
    resources :tasks do
      member do
        patch 'done'
      end
    end
    
    resources :relationships, only: [:create, :destroy]
    member do
      get 'follows'
      get 'followers'
      get 'follow_tasks'
    end
  end
  
  resources :rooms, only: [:create, :show]
  resources :messages, only: :create
  
  resources :tasks do
    resources :likes, only: [:create, :destroy]
  end

  resources :communities do
    resources :chats, only: [:index, :create, :destroy]
    resources :questions do
      patch 'resolve', on: :member
    end
  end

  post 'communities/:id', to: 'communities#join'
  delete 'communities/:id/exit', to: 'communities#exit', as: 'exit_community'

  resources :questions do
    resources :answers, only: [:create, :destroy]
    resources :me_toos, only: [:create, :destroy]
    resources :goods, only: [:create, :destroy]
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user

  validates :text, presence: true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: "ビジネス" },
    { id: 2, name: "趣味" },
    { id: 3, name: "その他" }
  ]
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :community

  validates :text, presence: true
end

app/models/community.rb
class Community < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category

  belongs_to :user
  has_many :user_communities, dependent: :destroy
  has_many :users, through: :user_communities
  has_many :chats, dependent: :destroy
  has_many :questions, dependent: :destroy

  validates :name, presence: true
  validates :text, presence: true

  # 検索
  scope :search, -> (search_params) do
    return if search_params.blank?

    category_is(search_params[:category_id])
      .text_like(search_params[:text])
  end
  scope :category_is, -> (category_id) { where(category_id: category_id) if category_id.present? }
  scope :text_like, -> (text) { where("text LIKE ?", "%#{text}%").or(where("name LIKE ?", "%#{text}%")) if text.present? }

  def joined_users
    user_ids = user_communities.pluck(:user_id)
    User.where(id: user_ids)
  end
end

app/models/good.rb
class Good < ApplicationRecord
  belongs_to :user
  belongs_to :question

  validates :question_id, uniqueness: { scope: :user_id }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :task

  validates :task_id, uniqueness: { scope: :user_id }
end

app/models/me_too.rb
class MeToo < ApplicationRecord
  belongs_to :user
  belongs_to :question

  validates :question_id, uniqueness: { scope: :user_id }
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  belongs_to :user

  validates :text, presence: true
end

app/models/occupation.rb
class Occupation < ActiveHash::Base
  self.data = [
    { id: 1, name: "会社員" },
    { id: 2, name: "自営業" },
    { id: 3, name: "アルバイト・パート" },
    { id: 4, name: "学生" },
    { id: 5, name: "その他" }
  ]
end

app/models/profile.rb
class Profile < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :occupation

  belongs_to :user
  has_one_attached :image

  # User検索用スコープ
  scope :occupation_is, -> (occupation_id) { where(occupation_id: occupation_id) if occupation_id.present? }
  scope :text_like, -> (text) { where("text LIKE ?", "%#{text}%") if text.present? }

  def occupation_name(user)
    occupation_id = user.profile.occupation_id
    return if occupation_id.blank?

    Occupation.find(occupation_id).name
  end

  # 新規登録時にプロフィール画像が指定されているかどうか
  def image_added?
    unless image.attached?
      image.attach(io: File.open('app/assets/images/default_user_image.png'), filename: 'default_user_image.png')
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :community
  has_one_attached :image
  has_many :answers, dependent: :destroy
  has_many :me_toos, dependent: :destroy
  has_many :goods, dependent: :destroy

  validates :title, :content, presence: true
  validates :state, inclusion: { in: [true, false] }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
  validates :follower_id, uniqueness: { scope: :following_id }
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms, dependent: :destroy
  has_many :users, through: :user_rooms
  has_many :messages, dependent: :destroy
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy

  validates :title, presence: true
  validates :state, inclusion: { in: [true, false] }

  # 特定のユーザーのタスクを取得
  scope :user_is, -> (user_id) { where(user_id: user_id) if user_id.present? }

  # 未完了のタスクを取得
  scope :not_completed, -> { where(state: false) }
  # 完了したタスクを取得
  scope :completed, -> { where(state: true) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates :password, format: { with: PASSWORD_REGEX, message: "は半角英数字で入力してください" }, on: :create

  has_one :profile, dependent: :destroy
  accepts_nested_attributes_for :profile, update_only: true
  has_many :tasks, dependent: :destroy

  has_many :user_rooms, dependent: :destroy
  has_many :rooms, through: :user_rooms
  has_many :messages, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :own_communities, class_name: "Community", dependent: :destroy
  has_many :user_communities, dependent: :destroy
  has_many :communities, through: :user_communities
  has_many :chats, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :me_toos, dependent: :destroy
  has_many :goods, dependent: :destroy

  # フォロー側
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id, dependent: :destroy
  has_many :followings, through: :active_relationships, source: :follower
  # フォロワー側
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id, dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :following

  # 引数のユーザが既にフォローしているかどうかの確認
  def follow?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end

  # 引数のtaskにいいね済みかどうかの確認
  def already_liked?(task)
    likes.where(task_id: task.id).exists?
  end

  # 引数のcommunityに参加済みかどうかの確認
  def already_joined?(community)
    user_communities.where(community_id: community.id).exists?
  end

  # 引数のquestionに「知りたい！」済みかどうかの確認
  def already_me_too?(question)
    me_toos.where(question_id: question.id).exists?
  end

  # 引数のquestionに「役に立った！」済みかどうかの確認
  def already_good?(question)
    goods.where(question_id: question.id).exists?
  end

  # ユーザ検索
  scope :search, -> (search_params) do
    # search_paramsが無かったら実行しない
    return if search_params.blank?

    # profileのtextが一致したuser
    profiles_text_match = Profile.text_like(search_params[:text])
    # profileのoccupationが一致したuser
    profiles_occupation_match = Profile.occupation_is(search_params[:occupation_id])

    # nameまたはprofileで取得したuser、かつ、occupationで取得したuser
    where("name LIKE ?", "%#{search_params[:text]}%")
      .or(where(id: profiles_text_match.pluck(:user_id)))
      .where(id: profiles_occupation_match.pluck(:user_id))
  end

  # ゲストユーザログイン時に「ゲスト」を検索or作成
  def self.guest
    find_or_create_by!(email: "guest@guest.com") do |user|
      user.name = "ゲスト"
      user.password = SecureRandom.hex(10)
    end
  end
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_good.html.erb
<% if current_user.already_good?(question) %>
  <%= link_to question_good_path(question, question_id: question.id), method: :delete, remote: true do %>
    <span class="good-text">役に立った!</span><i class="fas fa-thumbs-up un-good-btn"></i>
  <% end %>
<% else %>
  <%= link_to question_goods_path(question), method: :post, remote: true do %>
    <span class="good-text">役に立った!</span><i class="fas fa-thumbs-up good-btn"></i>
  <% end %>
<% end %>
<span class="question-response-count"><%= question.goods.count %></span>

app/views/shared/_me_too.html.erb
<% if current_user.already_me_too?(question) %>
  <%= link_to question_me_too_path(question, question_id: question.id), method: :delete, remote: true do %>
    <span class="metoo-text">知りたい!</span><i class="fas fa-exclamation un-metoo-btn"></i>
  <% end %>
<% else %>
  <%= link_to question_me_toos_path(question), method: :post, remote: true do %>
    <span class="metoo-text">知りたい!</span><i class="fas fa-exclamation metoo-btn"></i>
  <% end %>
<% end %>
<span class="question-response-count"><%= question.me_toos.count %></span>

app/views/shared/_tasks.html.erb
<div class="post-card">
  <div class="post-user">
    <% if task.user.profile.image.present? %>
      <%= link_to image_tag(task.user.profile.image.variant(resize: "50x50"), class:"user-image"), user_path(task.user) %>
    <% end %>
    <%= link_to task.user.name, user_path(task.user), class:"user-name" %>
    <span class="task-date"><%= l task.created_at, format: :short %></span>
  </div>
  <div class="post-title">
    <%= task.title %>
  </div>
  <div class="post-text"><%= task.text %></div>
  <% if user_signed_in? && (task.user.id == current_user.id) %>
    <div class="edit-area">
      <%= link_to edit_user_task_path(task.user, task.id), class: "edit-btn" do %>
        <i class="fas fa-pencil-alt"></i><span class="edit-btn-text">編集</span>
      <% end %>
      <%= link_to user_task_path(task.user, task.id), method: :delete, class:"delete-btn" do %>
        <i class="far fa-trash-alt"></i><span class="delete-btn-text">削除</span>
      <% end %>
      <% if !task.state %>
        <%= link_to "完了!!", done_user_task_path(task.user, task.id), method: :patch, class:"complete btn" %>
      <% else %>
        <span class="completed-btn">完了</span>
      <% end %>
    </div>
  <% end %>
  <div class="like-area">
    <% if current_user.already_liked?(task) %>
      <div>
        <%= link_to task_like_path(task.id, task_id: task.id), method: :delete, remote: true do %>
          <i class="fas fa-heart unlike-btn"></i>
        <% end %>
      </div>
    <% else%>
      <div>
        <%= link_to task_likes_path(task_id: task.id), method: :post, remote: true do %>
          <i class="fas fa-heart like-btn"></i>
        <% end %>
      </div>
    <% end %>
    <div class="like-count"><%= task.likes.count %></div>  
  </div>
</div>