config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get '/', to: 'users/sessions#new'
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :users, only: [:index, :show] do
    resources :tasks do
      member do
        patch 'done'
      end
    end
    
    resources :relationships, only: [:create, :destroy]
    member do
      get 'follows'
      get 'followers'
      get 'follow_tasks'
    end
  end
  
  resources :rooms, only: [:create, :show]
  resources :messages, only: :create
  
  resources :tasks do
    resources :likes, only: [:create, :destroy]
  end

  resources :communities do
    resources :chats, only: [:index, :create, :destroy]
    resources :questions do
      patch 'resolve', on: :member
    end
  end

  post 'communities/:id', to: 'communities#join'
  delete 'communities/:id/exit', to: 'communities#exit', as: 'exit_community'

  resources :questions do
    resources :answers, only: [:create, :destroy]
    resources :me_toos, only: [:create, :destroy]
    resources :goods, only: [:create, :destroy]
  end
end

app/models/community.rb
class Community < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category

  belongs_to :user
  has_many :user_communities, dependent: :destroy
  has_many :users, through: :user_communities
  has_many :chats, dependent: :destroy
  has_many :questions, dependent: :destroy

  validates :name, presence: true
  validates :text, presence: true

  # 検索
  scope :search, -> (search_params) do
    return if search_params.blank?

    category_is(search_params[:category_id])
      .text_like(search_params[:text])
  end
  scope :category_is, -> (category_id) { where(category_id: category_id) if category_id.present? }
  scope :text_like, -> (text) { where("text LIKE ?", "%#{text}%").or(where("name LIKE ?", "%#{text}%")) if text.present? }

  def joined_users
    user_ids = user_communities.pluck(:user_id)
    User.where(id: user_ids)
  end
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :set_community, only: [:edit, :update, :show, :join]
  before_action :move_to_index, only: [:edit, :update]

  def index
    @search_params = community_search_params
    @communities = Community.search(@search_params)
  end

  def new
    @community = Community.new
  end

  def create
    @community = Community.new(community_params)
    if @community.save
      user_community = @community.user_communities.new(user_id: current_user.id)
      user_community.save
      redirect_to community_path(@community)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @community.update(community_params)
      redirect_to community_path(@community)
    else
      render :edit
    end
  end

  def show
    # 参加ユーザー
    @joined_users = @community.joined_users.includes(profile: { image_attachment: :blob })
    # 参加ユーザーのタスク(サイドバー)
    @tasks = Task.user_is(@joined_users.pluck(:id))
    # うち未完了のタスク(一覧表示)
    @remain_tasks = @tasks.includes(user: { profile: { image_attachment: :blob } }).not_completed.order("created_at DESC")
    @questions = Question.where(community_id: @community.id)
  end

  def join
    user_community = @community.user_communities.new(user_id: current_user.id)
    if user_community.save
      redirect_to community_path(@community)
    else
      render :show
    end
  end

  def exit
    user_community = UserCommunity.find_by(user_id: current_user.id, community_id: params[:id])
    if user_community.destroy
      redirect_to community_path(params[:id])
    else
      render :show
    end
  end

  private

  def community_params
    params.require(:community).permit(:name, :category_id, :text).merge(user_id: current_user.id)
  end

  def set_community
    @community = Community.find(params[:id])
  end

  def move_to_index
    redirect_to communities_path if @community.user.id != current_user.id
  end

  def community_search_params
    params.fetch(:search, {}).permit(:text, :category_id)
  end
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/views/communities/_community_form.html.erb
<%= form_with model: community, local: true do |f|%>
  <%= render 'shared/error_messages', model: f.object %>
  <div class="community">
    <span class="community-label">名前 <span class="must">*必須</span></span>
    <%= f.text_field :name, placeholder: "コミュニティのなまえを入力しよう", class:"community-input" %>
  </div>
  <div class="community">
    <%= f.label "カテゴリー", class:"community-label" %>
    <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"form-box"}) %>
  </div>
  <div class="community">
    <%= f.label "説明", class:"community-label"%>
    <%= f.text_area :text, placeholder: "コミュニティの内容・目的を入力しよう", class:"community-input text" %>
  </div>
  
  <%= f.submit "登録", class:"community-submit btn" %>

<% end %>

app/views/communities/_community_sidebar.html.erb
<div class="menu-bar">
  <div class="menu-bar-box">
    <div class="community-name"><%= @community.name %></div>
    <div class="community-text"><%= @community.text %></div>
    <% if current_user.id == @community.user.id %>
      <%= link_to "編集する", edit_community_path(@community), class:"community-edit-btn" %>
    <% elsif current_user.already_joined?(@community) %>
      <%= link_to "脱退する", exit_community_path(@community), method: :delete, class:"community-exit btn" %>
    <% else %>
      <%= link_to "参加する", community_path(@community), method: :post, class:"community-join btn" %>
    <% end %>
    <div class="menu-items">
      <div class="community-members">
        参加ユーザー <span><%= @joined_users.count %></span>
      </div>
      <div class="community-completed-tasks">
        参加者の完了タスク <%= @tasks.where(state: true).count %>
      </div>
      <div class="question-and-answer">
        質問 <%= @questions.count%>
        解決 <%= @questions.where(state: true).count %>
      </div>
    </div>
  </div>
</div>

app/views/communities/edit.html.erb
<div class="menu-bar">
</div>
  
<div class="main">
  <div class="community-post-form">
    <%= render partial: "communities/community_form", locals: { community: @community } %>
  </div>
</div>

app/views/communities/index.html.erb
<div class="menu-bar">
  <div class="menu-bar-box">
    <p class="menu-bar-head"><i class="fas fa-search"></i>コミュニティ検索</p>
    <div class="menu-items">
      <%= form_with scope: :search, url: communities_path, method: :get, local: true do |f| %>
        <div class="search-field">
          <%= f.label :text, "キーワード", class:"search-label" %>
          <%= f.text_field :text, value: @search_params[:text], class:"search-text" %>
        </div>
        <div class="search-field">
          <%= f.label :catergory_id, "カテゴリー", class:"search-label" %>
          <%= f.collection_select(:category_id, Category.all, :id, :name, {selected: @search_params[:category_id], include_blank: "選択しない"}, {class:"search-category"}) %>
        </div>
        <div class="search-btn-area">
          <%= f.submit "検索", class:"search btn" %>
        </div>
      <% end %>
      <div class="search-cancel">
        <%= link_to "検索解除", communities_path, class:"search-cancel-btn" %>
      </div> 
    </div>
  </div>
</div>
  
<div class="main">
  <div class="search-heading">
    <div class="search-menu">
      <%= link_to "ユーザー", users_path, class:"search-navigation" %>
      <%= link_to "コミュニティ", communities_path, class:"search-navigation communities" %>
    </div>
    <%= link_to "コミュニティを作る", new_community_path, class:"community-create btn" %>
  </div>
  <div class="community-index-area">
    <div class="community-cards">
      <% @communities.each do |community| %>
        <%= link_to community_path(community) do %>
          <div class="community-card">
            <div class="community-card-head">
              <span class="community-title"><%= community.name %></span>
            </div>
            <div class="community-text">
              詳細：<%= community.text %>
            </div>
            <div class="community-category">
              カテゴリー：<%= community.category.name %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/communities/new.html.erb
<div class="menu-bar">
</div>
  
<div class="main">
  <div class="community-post-form">
    <%= render partial: "communities/community_form", locals: { community: @community } %>
  </div>
</div>

app/views/communities/show.html.erb
<%= render "communities/community_sidebar" %>

<div class="main">
  <div class="community-main-heading">
    <div class="community-main-menu">
      <%= link_to community_path(@community), class:"community-navigation task" do %>
        <%= image_tag "check.png", size: "18x18", class: "task-icon" %><span>みんなのタスク</span>
      <% end %>
      <%= link_to community_chats_path(@community), class:"community-navigation" do %>
        <%= image_tag "chat_man.png", size: "18x18", class: "chat-icon" %><span>チャット</span>
      <% end %>
      <%= link_to community_questions_path(@community), class:"community-navigation" do %>
        <%= image_tag "question.png", size: "18x18", class: "question-icon" %><span>質問</span>
      <% end %>
    </div>
  </div>
  <div class="community-user-tasks">
    <div class="communities-posts-cards">
      <% @remain_tasks.each do |task| %>
        <span id="task_<%= task.id %>">
          <%= render partial: "shared/tasks", locals: { task: task } %>
        </span>
      <% end %>
    </div>
  </div>
</div>